# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/OpenR1-Math-cn_k12-86k
system_prompt: "Please reason step by step, and put your final answer within \\boxed{}."

# GRPO trainer config
beta: 0.001
bf16: true
do_eval: false
eval_strategy: "no"
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.9
do_eval: false
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-1.5B-Instruct-GRPO
hub_strategy: every_save
learning_rate: 2.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant_with_warmup
max_grad_norm: 0.2
max_prompt_length: 512
max_completion_length: 4096
max_steps: -1
num_generations: 8
num_train_epochs: 1
output_dir: data/Qwen2.5-1.5B-Instruct-GRPO
overwrite_output_dir: true
per_device_train_batch_size: 16
push_to_hub: false
report_to:
- wandb
reward_funcs:
- accuracy
reward_weights:
- 1.0
save_strategy: "epoch"
save_total_limit: 1
seed: 42
temperature: 0.7
wandb_entity: huggingface 
wandb_project: open-r1
warmup_ratio: 0.1
