# Model arguments
model_name_or_path: open-r1/Qwen2.5-Coder-7B-Instruct-SFT
model_revision: v00.08-step-000001280
torch_dtype: bfloat16
attn_implementation: flash_attention_2
# Data training arguments
dataset_name: open-r1/verifiable-coding-problems-python-10k_decontaminated
dataset_configs:
- all
num_processes: 7
ddp_find_unused_parameters: false
# GRPO trainer config
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
bf16: true
do_eval: false
eval_strategy: "no"
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: open-r1/Qwen2.5-Coder-7B-Instruct-SFT-GRPO
hub_model_revision: v00.00
hub_strategy: every_save
learning_rate: 1.0e-06
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 31744
max_steps: -1
num_train_epochs: 5
num_generations: 7
output_dir: data/open-r1/Qwen2.5-Coder-7B-Instruct-SFT-GRPO-v00.00
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 2
push_to_hub: true
report_to:
- wandb
seed: 42
warmup_ratio: 0.1

# Saving and eval callbacks
save_strategy: "steps"
save_steps: 25
callbacks:
- push_to_hub_revision
benchmarks:
- lcb

reward_funcs:
# - code
- code_format
reward_weights:
# - 1.0
- 0.1