# Model arguments
model_name_or_path: Qwen/Qwen2.5-Coder-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: PrimeIntellect/SYNTHETIC-1-SFT-Data
dataset_configs:
- all
dataset_num_proc: 48

# SFT trainer config
callbacks:
- push_to_hub_revision
benchmarks:
- aime24
- aime25
- math_500
- gpqa
- lcb
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: open-r1/Qwen2.5-Coder-3B-Instruct-SFT-SYNTHETIC-1-v00.00
hub_strategy: every_save
learning_rate: 1.0e-06
log_level: info
logging_first_step: true
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: true
max_seq_length: 32768
max_steps: -1
num_train_epochs: 3
output_dir: data/Qwen2.5-Coder-3B-Instruct-SFT-SYNTHETIC-1-v00.00
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
push_to_hub: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 200
save_total_limit: 1
seed: 42
use_liger: true
wandb_entity: huggingface
wandb_project: open-r1
warmup_ratio: 0.05